# Generated by ChatGPT

import sys

if sys.platform.startswith("win"):
    import msvcrt
    def getkey():
        ch = msvcrt.getch()
        if ch in {b'\x00', b'\xe0'}:
            ch2 = msvcrt.getch()
            mapping = {
                b'H': "UP",
                b'P': "DOWN",
                b'K': "LEFT",
                b'M': "RIGHT",
            }
            return mapping.get(ch2, f"UNKNOWN({ch+ch2})")
        else:
            return ch.decode('utf-8', errors='ignore')

else:
    import tty, termios
    def getkey():
        fd = sys.stdin.fileno()
        old_settings = termios.tcgetattr(fd)
        try:
            tty.setraw(fd)
            ch = sys.stdin.read(1)
            if ch == '\x1b':
                seq = ch + sys.stdin.read(2)
                mapping = {
                    "\x1b[A": ("UP",seq.encode()),
                    "\x1b[B": ("DOWN",seq.encode()),
                    "\x1b[D": ("LEFT",seq.encode()),
                    "\x1b[C": ("RIGHT",seq.encode()),
                }
                return mapping.get(seq, ("UNKNOWN",seq.encode()))
            else:
                return ch
        finally:
            termios.tcsetattr(fd, termios.TCSADRAIN, old_settings)
